Repository USSBA/sba-gov-katana, pull requests merged in 2019-09, with the labels that each got.

#923 TA-2914 added services section
  src/client/components/templates/district-office/district-office.jsx
  src/client/components/templates/district-office/district-office.scss
  test/jest/client/components/templates/district-office/district-office.test.js
Labels: Ready for Review, sbagov

#925 TA-2911 twitter section for district office
  src/client/components/templates/district-office/district-office.jsx
  src/client/components/templates/district-office/district-office.scss
  test/jest/client/components/templates/district-office/district-office.test.js
Labels: Ready for Review, sbagov

#927 TA-3104 updated articles request
  src/client/components/organisms/news-releases/news-releases.jsx
Labels: Ready for Review, sbagov

#928 TA-2912 district office main location
  src/client/components/atoms/card-container/card-container.jsx
  src/client/components/atoms/card-container/card-container.scss
  src/client/components/atoms/index.js
  src/client/components/molecules/contact-card/contact-card.jsx
  src/client/components/molecules/contact-card/contact-card.scss
  src/client/components/organisms/generic-card-collection/generic-card-collection.jsx
  src/client/components/organisms/generic-card-collection/generic-card-collection.scss
  src/client/components/organisms/index.jsx
  src/client/components/templates/district-office/district-office.jsx
  src/client/components/templates/district-office/district-office.scss
  test/jest/client/components/atoms/card-container/card-container.test.jsx
  test/jest/client/components/molecules/contact-card/__snapshots__/contact-card.test.jsx.snap
  test/jest/client/components/molecules/contact-card/contact-card.test.jsx
  test/jest/client/components/organisms/generic-card-collection/generic-card-collection.test.jsx
  test/jest/client/components/templates/district-office/district-office.test.js
  test/jest/client/components/templates/person/__snapshots__/person.test.jsx.snap
  test/jest/client/components/templates/person/person.test.jsx
Labels: Ready for Review, sbagov

#931 TA-2922 added no-results state and unit test
  src/client/components/molecules/quick-links/quick-links.jsx
  test/jest/client/components/molecules/quick-links/__snapshots__/quick-links.test.js.snap
  test/jest/client/components/molecules/quick-links/quick-links.test.js
Labels: Ready for Review, sbagov

#932 TA-2504 login link removed
  src/client/components/organisms/header-footer/mini-nav/mini-nav.jsx
  src/client/translations.js
Labels: sbagov

#930 TA-2913 add alternate locations to location info
  src/client/components/molecules/contact-card/contact-card.jsx
  src/client/components/organisms/index.jsx
  src/client/components/organisms/location-info-section/location-info-section.jsx
  src/client/components/organisms/location-info-section/location-info-section.scss
  src/client/components/templates/district-office/district-office.jsx
  src/client/components/templates/district-office/district-office.scss
  test/jest/client/components/molecules/contact-card/contact-card.test.jsx
  test/jest/client/components/organisms/location-info-section/location-info-section.test.jsx
  test/jest/client/components/templates/district-office/district-office.test.js
Labels: WIP, sbagov

#934 add link to footer
  src/client/components/organisms/header-footer/footer/footer.jsx
  src/client/translations.js
  test/jest/client/components/organisms/footer/__snapshots__/footer.test.jsx.snap
Labels: Ready for Review, sbagov

#933 TA-2927 success stories page
  src/client/components/pages/blog-category/blog-category-page.jsx
  src/client/components/routes.jsx
  test/jest/client/components/pages/blog-category/blog-category.test.js
Labels: Ready for Review, sbagov

#938 TA-2967 center main loader
  src/client/components/pages/district-office-page/district-office-page.jsx
  src/client/components/pages/district-office-page/district-office-page.scss
Labels: Ready for Review, sbagov

#935 TA-3004 added success stories and unit tests
  src/client/components/organisms/blog-category-deck/blog-category-deck.jsx
  src/client/components/pages/blogs-landing/blogs-landing.jsx
  test/jest/client/components/pages/blogs-landing/blogs-landing.test.js
Labels: Ready for Review, sbagov

#940 Feature ta 3178 - IE11 Layout Fixes
  src/client/components/atoms/decorative-dash/decorative-dash.jsx
  src/client/components/atoms/decorative-dash/decorative-dash.scss
  src/client/components/molecules/contact-card/contact-card.scss
  src/client/components/molecules/quick-links/quick-links.jsx
  test/jest/client/components/molecules/call-to-action/__snapshots__/call-to-action.test.jsx.snap
  test/jest/client/components/molecules/card/__snapshots__/card.test.jsx.snap
  test/jest/client/components/molecules/quick-links/__snapshots__/quick-links.test.js.snap
  test/jest/client/components/molecules/readmore/__snapshots__/readmore.test.jsx.snap
  test/jest/client/components/organisms/courses-layout/__snapshots__/courses-layout.test.jsx.snap
  test/jest/client/components/organisms/document-article-lookup/__snapshots__/document-article-lookup.test.jsx.snap
  test/jest/client/components/pages/blog-category/blog-category.test.js
Labels: Ready for Review, sbagov

#936 TA-3005 use featured image for posts on blog category page
  src/client/components/pages/blog-category/blog-category-page.jsx
  test/jest/client/components/pages/blog-category/blog-category.test.js
Labels: Ready for Review, sbagov

#941 TA-3214 blogs landing page featured-image
  src/client/components/organisms/blog-category-deck/blog-category-deck.jsx
  src/client/components/organisms/success-stories/success-stories.jsx
  test/jest/client/components/pages/blog-category/blog-category-response-faker.js
  test/jest/client/components/pages/blog-category/blog-category.test.js
  test/jest/client/components/test-data/district-office-blogs.json
Labels: Ready for Review, sbagov

#943 made styling changes to district office page
  src/client/components/organisms/news-releases/news-releases.jsx
  src/client/components/organisms/success-stories/success-stories.jsx
  src/client/components/templates/district-office/district-office.jsx
  src/client/components/templates/district-office/district-office.scss
Labels: Ready for Review, sbagov

#944 TA-3178 added p tag to document link
  src/client/components/molecules/quick-links/quick-links.jsx
  test/jest/client/components/molecules/quick-links/__snapshots__/quick-links.test.js.snap
Labels: Ready for Review, sbagov
