Repository USSBA/sba-gov-katana, pull requests merged in 2019-08, with the labels that each got.

#908 Feature ta 2854 Add date range logic for events
  config/amy.yml
  config/avery.yml
  config/brian.yml
  config/kevin.yml
  config/mint.yml
  config/pat.yml
  config/ryan.yml
  config/test.yml
  src/client/components/pages/event-lookup-page/event-lookup-page.jsx
  src/server.js
  test/jest/client/components/pages/event-lookup-page/event-lookup-page.test.jsx
Labels: WIP, sbagov

#910 TA-2926 added district office page and template
  src/client/components/pages/district-office-page/district-office-page.jsx
  src/client/components/pages/root-page.jsx
  src/client/components/routes.jsx
  src/client/components/templates/district-office/district-office.jsx
  test/jest/client/components/pages/district-office-page/district-office-page.test.js
Labels: Ready for Review, sbagov

#912 TA-2918 added sign up component and updated tests
  src/client/components/atoms/text-input/text-input.jsx
  src/client/components/organisms/modals/leave-sba-modal/leave-sba-modal.jsx
  src/client/components/organisms/paging-lookup/paging-lookup.jsx
  src/client/components/templates/district-office/district-office.jsx
  src/client/components/templates/district-office/district-office.scss
  src/client/services/utils.js
  test/jest/client/components/molecules/newsletter-form/newsletter-form.test.jsx
  test/jest/client/components/organisms/header-footer/disaster-alert/disaster-alert.test.jsx
  test/jest/client/components/organisms/hero/hero.test.jsx
  test/jest/client/components/organisms/homepage/front-page-hero/front-page-hero.test.jsx
  test/jest/client/components/pages/root-page.test.js
  test/jest/client/components/templates/district-office/district-office.test.js
  test/jest/setup.js
Labels: Ready for Review, sbagov

#911 TA-2920 add CTA to district office page
  public/assets/images/local-assistance/Planning2.png
  src/client/components/molecules/call-to-action/call-to-action.jsx
  src/client/components/templates/district-office/district-office.jsx
  src/client/components/templates/district-office/district-office.scss
  test/jest/client/components/molecules/call-to-action/__snapshots__/call-to-action.test.jsx.snap
  test/jest/client/components/molecules/call-to-action/call-to-action.test.jsx
  test/jest/client/components/templates/district-office/district-office.test.js
Labels: Ready for Review, sbagov

#914 TA-2921 created lender match component
  src/client/components/templates/district-office/district-office.jsx
  src/client/components/templates/district-office/district-office.scss
  test/jest/client/components/templates/district-office/district-office.test.js
Labels: Ready for Review, sbagov

#915 Ta 2921 hotfix
  src/client/components/templates/district-office/district-office.jsx
Labels: Ready for Review, sbagov

#916 Feature ta 2919
  src/client/components/templates/district-office/district-office.jsx
  src/client/components/templates/district-office/district-office.scss
  test/jest/client/components/pages/district-office-page/district-office-page.test.js
  test/jest/client/components/templates/district-office/district-office.test.js
  test/jest/client/components/test-data/events.json
Labels: Ready for Review, sbagov

#918 TA-0000 hotfix to update url on events button
  src/client/components/templates/district-office/district-office.jsx
Labels: Ready for Review, sbagov

#901 T1-1385 Remove register link
  config/default.yaml
  src/client/components/organisms/header-footer/mini-nav/mini-nav.jsx
  src/server.js
Labels: WIP

#919 TA-2859 add office filter to article lookup
  src/client/components/organisms/document-article-lookup/document-article-lookup.jsx
  src/client/components/organisms/document-article/document-article.jsx
  src/client/components/organisms/paging-lookup/paging-lookup.jsx
  src/client/components/pages/article-lookup-page/article-lookup-page.jsx
  test/jest/client/components/organisms/document-article-lookup/__snapshots__/document-article-lookup.test.jsx.snap
  test/jest/client/components/pages/article-lookup-page/article-lookup-page.test.jsx
Labels: Ready for Review, sbagov

#920 TA-2917 added news release section to office page
  src/client/components/molecules/detail-card/detail-card.jsx
  src/client/components/organisms/index.jsx
  src/client/components/organisms/news-releases/news-releases.jsx
  src/client/components/organisms/news-releases/news-releases.scss
  src/client/components/templates/district-office/district-office.jsx
  src/client/components/templates/district-office/district-office.scss
  test/jest/client/components/organisms/document-article-lookup/__snapshots__/document-article-lookup.test.jsx.snap
  test/jest/client/components/organisms/news-releases/news-releases.test.js
  test/jest/client/components/templates/district-office/district-office.test.js
  test/jest/client/components/test-data/news-releases/errorNewsReleasesData.json
  test/jest/client/components/test-data/news-releases/noNewsReleasesData.json
  test/jest/client/components/test-data/news-releases/oneNewsReleasesData.json
  test/jest/client/components/test-data/news-releases/threeNewsReleasesData.json
Labels: Ready for Review, sbagov

#922 TA-2908 district office hero
  package.json
  src/client/components/organisms/hero/hero.jsx
  src/client/components/templates/district-office/district-office.jsx
  test/jest/client/components/organisms/news-releases/news-releases.test.js
  test/jest/client/components/pages/district-office-page/district-office-page.test.js
  test/jest/client/components/templates/district-office/district-office.test.js
  test/jest/client/components/test-data/news-releases/oneNewsReleasesData.json
  test/jest/client/components/test-data/news-releases/threeNewsReleasesData.json
Labels: Ready for Review, sbagov
